site_name: Apex-yuan
site_url: https://blog.csdn.net/xiaoyuanwuhui
site_description: Apex-yuan's notes.
site_author: Apex-yuan

repo_url: https://github/Apex-yuan/mydocs/
edit_uri: ""

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django
        - c

nav:
    - Preface: 
        - Preface: index.md
    - Arduino:
        - Arduino内核中的知识点解读: Arduino/Arduino内核中的知识点解读.md
    - STM32: 
        - STM32HAL库串口处理---中断收发: STM32/STM32HAL库串口处理---中断收发.md
        - STM32HAL库微秒延时函数的实现: STM32/STM32HAL库微秒延时函数的实现---DWT和SysTick.md
        - STM32F407_HAL_TIM_DMA驱动WS2812: STM32/STM32F407_HAL_TIM_DMA驱动WS2812.md
        - 彻底搞清printf在STM32上的使用: STM32/彻底搞清printf在STM32上的使用.md
    - Arduino_Core_STM32:
        - Arduino_Core_STM32---pinMode()实现分析: Arduino_Core_STM32/Arduino_Core_STM32---pinMode()实现分析.md
    - BalanceCar:
        - 平衡车-原理篇: BalanceCar/平衡车-原理篇.md
    - C:
        - C语言知识点---局部数组的长度可用变量表示: C/C语言知识点---局部数组的长度可用变量表示.md
        - 利用#undef实现特定模块的调试输出: C/利用#undef实现特定模块的调试输出.md
    - Communication: 
        - 串口协议包的接收及解析处理: Communication/串口协议包的接收及解析处理.md
    - Marlin:
        - marlin应用到STM32实践（续）: Marlin/marlin应用到STM32实战（续）.md
    - PID:
        - Improving the Beginner’s PID: PID/Improving the Beginner’s PID.md
    - Python:
        - python_learning: Python/python_learning.md

extra_css:
    - css/extra.css

markdown_extensions:
    - toc:
        permalink: 
    - admonition
    - def_list
    - mdx_gh_links:
        user: Apex-yuan
        repo: mydocs

copyright: Copyright &copy; 2020 <a href="https://github/Apex-yuan.com">Apex-yuan</a>, Maintained by the <a href="/about/release-notes/#maintenance-team">Apex-yuan</a>.
google_analytics: ['UA-27795084-5', 'mkdocs.org']

plugins:
    - search
