site_name: Apex-yuan
site_url: https://github/Apex-yuan.com
site_description: Apex-yuan's notes.
site_author: Apex-yuan

repo_url: https://github/Apex-yuan.com
edit_uri: ""

theme:
    name: readthedocs
    highlightjs: true
    hljs_languages:
        - yaml
        - django
        - c

nav:
    - Preface: 
        - 前言: index.md
    - Arduino:
        - Arduino内核中的知识点解读: Arduino/Arduino内核中的知识点解读.md
    - STM32:
        - STM32 HAL: 
            - STM32HAL库串口处理---中断收发: STM32/STM32HAL库串口处理---中断收发.md
            - STM32HAL库微秒延时函数的实现: STM32/STM32HAL库微秒延时函数的实现---DWT和SysTick.md
    - Arduino_Core_STM32:
        - Arduino_Core_STM32---pinMode()实现分析: Arduino_Core_STM32/Arduino_Core_STM32---pinMode()实现分析.md
    - BalanceCar:
        - 平衡车-原理篇: BalanceCar/平衡车-原理篇.md
    - Marlin:
        - marlin应用到STM32实践（续）: marlin应用到STM32实战（续）.md
    - PID:
        - Improving the Beginner’s PID: Improving the Beginner’s PID.md

#extra_css:
#    - css/extra.css

markdown_extensions:
    - toc:
        permalink: 
    - admonition
    - def_list
    - mdx_gh_links:
        user: Apex-yuan
        repo: mydocs

copyright: Copyright &copy; 2020 <a href="https://github/Apex-yuan.com">Apex-yuan</a>, Maintained by the <a href="/about/release-notes/#maintenance-team">Apex-yuan</a>.
google_analytics: ['UA-27795084-5', 'mkdocs.org']

plugins:
    - search
