site_name: xiaoyuan's note
site_author: Apex-yuan

nav:
    - STM32:
        - STM32 HAL: 
            - STM32/aaa.md
            - STM32/bbb.md
        
        
#theme: readthedocs

theme: 
    name: readthedocs 
    highlightjs: true 
    hljs_languages: 
        - yaml 
        - django 