site_name: xiaoyuan's note
site_author: Apex-yuan

nav:
    - STM32:
        - STM32 HAL: 
            - STM32/STM32HAL库串口处理---中断收发.md
            - STM32/STM32HAL库微秒延时函数的实现---DWT和SysTick.md
        
        
theme: readthedocs
